# https://tools.keycdn.com/sha256-online-generator
@hostname=entu.app/api
@account=esmuuseum
###
# auth
GET {{hostname}}/auth?account={{account}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_key}}

###
# account
GET {{hostname}}/{{account}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# entities GET
GET {{hostname}}/{{account}}/entity?props=_type HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# entity GET
GET {{hostname}}/{{account}}/entity/66d6ead6f2daf46b3143eefb HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# entity GET folder
GET {{hostname}}/{{account}}/entity?_type.string=folder HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# entity GET VR
GET {{hostname}}/{{account}}/entity?_type.string=vabaduse rist HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# entity GET VRK
GET {{hostname}}/{{account}}/entity?_type.string=vrkavaler HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# POST vrk
POST {{hostname}}/{{account}}/entity HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

[
    {"type": "_type", "string": "vrkavaler", "reference": "66d56de42acf2af0bc794b9d"},
    {"type": "forename", "string": "Jane4"},
    {"type": "surname", "string": "Doe4"}
]

###
# Aggregate entity
GET {{hostname}}/{{account}}/entity/66d87898f2daf46b3144ce21/aggregate HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

###
# DELETE entity
DELETE {{hostname}}/{{account}}/entity/66d771c4f2daf46b3143f057
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

###
# entity GET VRK id's
#GET {{hostname}}/{{account}}/entity?_type.string=vrkavaler&props=_id HTTP/1.1
GET https://entu.app/api/esmuuseum/entity?_type.string=vrkavaler&props=_id
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}